Data/PackagesSearchResults.cs

Prerelease-only packages will not show up in results, this pr will fix this.
Example: https://www.nuget.org/packages/Sejil/

Include pre-release packages in search results

---

Data/CecilExtensions.cs

CecilExtensions was rendering out paramters as ref. Fixes #51

Out parameters in type docs

---

Data/TypeDocumentation.cs

Resolves #44.
Renders the `@name` of a `<typeparamref>` XML documentation comment element as an inline code type reference.

Render <typeparamref> XML doc comments

---

Data/TypeDocumentation.cs

This should fix #42.
Adds some logic for handling `@langword` attributes in `<see>` XML documentation comment elements. The value of `@langword` gets rendered as an inline code keyword.

Render <see langword="..." /> XML doc comments

---

Data/TypeDocumentation.cs
wwwroot/css/site.css

I also added some clarification comments for the various c-* CSS classes as I was having a hard time figuring them out. Are the abbreviation choices in reference to some documentation? I'd be happy to read it and update the comments accordingly (assuming you're open to having the comments added or want something else done instead).
This should fix #6.

Add handling for typeparamref and seealso XML doc tags

---

Data/NugetPackageSource.cs
Data/NugetPackageSources.cs
Data/PackageData.cs
Data/PackageVersions.cs
Data/PackagesSearchResults.cs
Pages/index.cshtml
Pages/packages/details.cshtml
Startup.cs
appsettings.json

This adds the ability to configure multiple package sources.  This should solve most of what #13 (and the duplicate #50 ) is asking for.  This does not currently allow for authenticated sources, but it should be a simple addition of more configuration values and adding them to headers.
Adding a new package source is as simple as adding a new entry in the appsettings.json, under NugetPackageSources.  If the NugetPackageSources section is missing completely, it will default to the current nuget.org source.
In order to get this to work with our internal version of Nuget Gallery, I had to add some specific endpoints, because it does not support v3, but anything that does should be able to simply swap out urls.

Allow for configuration of multiple package sources

---

Pages/packages/index.cshtml

With a max-height of 3em, Safari always displays scroll bars. By increasing the max-height to 5em and changing overflow:scroll to overflow:auto, the scroll bars disappear making the page much more pleasant to look at.
*Left*: `max-height:3em;overflow:scroll`
*Right*: `max-height:5em;overflow:auto`

Improve display of search results in Safari

---

appsettings.json

See: https://devblogs.microsoft.com/nuget/new-and-improved-nuget-search/
For example: https://azuresearch-usnc.nuget.org/query?prerelease=true&semVerLevel=2.0.0&q=Microsoft.Extensions.Logging
We will be deleting the old search service soon and the URL will no longer exist.

Update to use NuGet.org's new search service

---

wwwroot/css/site.css

The scroll bars in the Types section of the Package details page are not needed most of the time, so I made the scroll bars optional for `.long-item-list`, just like they are for `ul.pkglist`.
Also, I can see that there scroll bars on the search results / package list page are always visible on fuget.org, despite this change: https://github.com/praeclarum/FuGetGallery/blob/d6deda7afe191d6dfcaa7dd84a988b403e4f5f18/Pages/packages/index.cshtml#L29
And thanks for creating this project ❤

Make Types scroll bars in package details optional

---

Data/PackageVersions.cs
FuGetGallery.csproj

Fixes https://github.com/praeclarum/FuGetGallery/issues/63.
With this change, prerelease versions of packages are sorted correctly:

Use NuGet.Versioning.SemanticVersion to correctly compare package versions

---

Data/PackagesSearchResults.cs

Azure Artifacts supports the v3 NuGet Search API, but doesn't return a `totalDownloads` property for each package. (I can't provide an example URL, sorry.) We now just set this property (which isn't currently used) to zero if it's missing in the JSON.
Without this change, searching displays the following error in the UI:
> System.ArgumentNullException: Value cannot be null. Parameter name: value at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value) at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value) at FuGetGallery.PackagesSearchResults.Read(String json) in C:\Code\FuGetGallery\Data\PackagesSearchResults.cs:line 45 at FuGetGallery.PackagesSearchResults.ResultsCache.GetValueAsync(String q, HttpClient httpClient, CancellationToken token) in …

Allow 'totalDownloads' to be missing from search results JSON

---

Data/PackageVersions.cs

`SemanticVersion` only supports three part (major.minor.patch) version numbers (plus suffixes); any version number not fitting that format will have a `SemanticVersion` of `null` and thus be considered equal.
This commit restores the previous version parsing logic (before #83) as a fallback for when `SemanticVersion` fails to parse a version number.
I ran into this when displaying packages from a feed that used Windows-style four-part version numbers instead of three-part version numbers. They were all considered to have the same `null` SemanticVersion and appeared unordered in the UI.
As per 1c63a21d8f55df79e2022c885dc21b2a394afded there must previously have been packages with four-part version numbers (since the code was extended to handle them); this PR reinstates support for packages …

Fall back to manual version parsing if SemanticVersion fails

---

Data/License.cs

FuGet incorrectly identifies MySql.Data as using the MIT license: https://www.fuget.org/packages/MySql.Data
This occurs because the license URL is https://downloads.mysql.com/docs/licenses/connector-net-8.0-gpl-en.pdf which doesn't match any known license. When this file is downloaded, its plain text (of the PDF source) arbitrarily matches "MIT License", which occurs in the file.
Rather than adding more sophisticated logic for (for example) only string matching on files <1KB or rejecting matches on multiple licenses, this simply hard-codes MySql.Data's license URL as matching GPL 2 (which is the license claimed by the package).

Special-case the MySql.Data GPL license

---

Data/PackageAssemblyXmlDocs.cs

Previously the code to read XmlDoc expected `see` elements to have a `cref` attribute. However, in case of `<see langword="xxx" />`, this resulted in a `NullReferenceException`.
This PR fixes this and returns the correct langword as text element.

NullReferenceException when encountering <see langword="xxx" />

---

Data/PackagesSearchResults.cs

Currently, if there are no results for the search term, an empty AggregateException will be generated and returned. 
As an example see: https://www.fuget.org/packages?q=ThisSearchTermWillProduceNoResults
I have added an extra check to ensure that an AggregateException is only returned if there are actually some exceptions that were thrown.

Only return an AggregateException if exceptions were thrown

---

Pages/packages/details.cshtml

Fixes #57.
This won't fix cached information in cached HTTP responses or localStorage.

Escape strings for JavaScript

---

Pages/packages/details.cshtml

Preserves diff options when navigating between frameworks. Saves a lot of time comparing different assembly versions

Preserve version diff options

---

Startup.cs
appsettings.json

This fixes #75.
Also upgrade to `registration4` endpoint, which includes more package versions (see #95).

Support SemVer 2 packages

---

Pages/packages/index.cshtml

This avoids blank output (e.g., at https://www.fuget.org/packages?q=ABCXYZ) which can make it unclear whether the search worked or not.

Display a message when a search has no results

---

Pages/packages/details.cshtml

This makes it clearer when there are no dependents, rather than just hiding the heading

Adds "none" to dependents list if none

---

appsettings.json

I rebuilt nuget.org registration job to have better performance. As part of this rollout, registration5 (not registration4) is now the latest version. See https://github.com/NuGet/NuGetGallery/issues/7734 for more details.

Use registration5 instead of registration4

---

Data/CecilExtensions.cs
FuGetGallery.csproj

Right now it use 0.10 dependency from ICSharpCode.Decompiler, which fails on some assemblies. E.g. https://www.fuget.org/packages/Oracle.ManagedDataAccess

Add explicit Mono.Cecil dependency

---

Data/PackageVersions.cs

Fixes #95.
When the NuGet API returns package versions as part of the response, the code only read the versions from the last page. It now reads the versions from all pages, whether they're returned inline or referenced via a secondary URL.

Read all pages of a package's results

---

Data/PackageVersions.cs

Fixes https://github.com/praeclarum/FuGetGallery/issues/118.
If there are no stable packages, shows the last pre-release package by default.

Default to a pre-release package if there are no others

---

Data/PackageData.cs
Data/PackageVersions.cs
Pages/packages/badges.cshtml

For example, this is currently the case for the BaGet.Protocol package.
Before this pull request, an error is displayed when accessing the [BaGet.Protocol](https://www.fuget.org/packages/BaGet.Protocol) page without specifying a version:
```
System.IO.InvalidDataException: End of Central Directory record could not be found.
at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
at FuGetGallery.PackageData.Read(MemoryStream bytes, HttpClient httpClient) in D:\home\site\repository\Data\PackageData.cs:line 118
at …
```

Default to latest pre-release version if the package has only pre-release versions

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/library-scripts/azcli-debian.sh
.vscode/launch.json

Added a configuration for devcontainers, for use in VS Code, Visual Studio 2019 and GitHub Codespaces. It's using the default configuration provided by Microsoft
I've also tweaked the launch.json for vscode as this was pointing to netcoreapp2.0 instead of netcoreapp2.1.

Add DevContainer Configuration

---

Data/PackageVersions.cs

This fixes an issue with the "diff" feature when one of the package versions is a pre-release package with an uppercase character. Previously this would fall into the first `v == null` case and the diff would end up targeting the latest non-pre-release version.
I fixed this as I was listening to your podcast and was reminded this was the one bug that ... bugged me about fuget. Didn't realize Merge Conflict existed before today, so happy to have discovered that as well.

Fix issue with diffing with pre-release pkg containing uppercase char

---

web.config

Allows all file extensions that are disabled by default. From https://docs.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/fileextensions/.
Fixes https://github.com/praeclarum/FuGetGallery/issues/122.

Allow all file extensions

---

.gitignore
Data/PackageAssembly.cs
Data/PackageAssemblyXmlDocs.cs
Data/PackageData.cs
Data/PackageFile.cs
Pages/packages/details.cshtml

This is a proof of concept (very rough) of an optimization to avoid downloading and caching entire packages. It uses [the structure of the zip archive](https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.3.TXT) and [HTTP range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) to only download "slices" of the zip package instead of downloading the whole thing. 
It seems that in a lot of these large packages the "bloat" is due to large native binaries that fuget doesn't do anything with. No reason to download and cache those, unfortunately with the current approach everything comes along for the ride.
The bulk of the changes are in PackageData.cs, and replace usage of the ZipArchive class with manually requesting sub-ranges of the package to retrieve just the …

package download optimization POC

---

FuGetGallery.csproj
Program.cs

Now that the project is targeting .NET 5, C# 9.0 features can begin to be used.
I thought a nice one to clean up some unnecessary boilerplate is the top-level statements feature.

Use C# 9 top-level statements

---

Data/PackageData.cs
Data/PackageTargetFramework.cs

This restores the work that @praeclarum did in #144, which were undone when I added the download optimizations. The local caching should still provide a performance improvement. Caching of the zip archive table of contents, while the payload is very small, avoids 3 HTTP round trips required to discover the location of the TOC.
I'm slightly worried about what the behavior will be when the local disk eventually fills up. I think the behavior of the code will be fine, it should revert to pulling over HTTP. The full disk might lead to other issues though.
These bits can be previewed at https://pfluget-test.azurewebsites.net/ which is running in the smallest free Azure service plan. First hit might be slow, as the service will likely need to start up.

Cache files locally
